In [7]:
import numpy as np
dataset = np.genfromtxt('data/normal_distribution.csv', delimiter=',')

In [9]:
# indexing the second row
dataset[1]

array([ 92.02628776,  97.10439252,  99.32066924,  97.24584816,
        92.9267508 ,  92.65657752, 105.7197853 , 101.23162942])

In [30]:
# indexing the last element of the dataset (last row)
dataset[-1]

array([ 94.11176915,  99.62387832, 104.51786419,  97.62787811,
        93.97853495,  98.75108352, 106.05042487, 100.07721494])

In [13]:
# indexing the first value of the second row
dataset[1, 0]

92.02628776

In [31]:
# indexing the last value of the second-to-last row
dataset[-2, -1]

103.83852459

In [32]:
# slicing
# an intersection of four elements (2x2) of the first two rows and first two columns
dataset[1:3, 1:3]

array([[97.10439252, 99.32066924],
       [95.17750125, 90.93318132]])

In [18]:
# every second element of the fifth row
dataset[6, ::2]

array([101.20862522, 100.28690912,  93.37126331, 100.79478953])

In [33]:
# reverse the entry order, selecting the first two rows in reverse order
dataset[-1, ::-1]

array([100.07721494, 106.05042487,  98.75108352,  93.97853495,
        97.62787811, 104.51786419,  99.62387832,  94.11176915])

In [23]:
# split our dataset horizontally into three equal parts
np.hsplit(dataset, (3,))

[array([[ 99.14931546, 104.03852715, 107.43534677],
        [ 92.02628776,  97.10439252,  99.32066924],
        [ 95.66253664,  95.17750125,  90.93318132],
        [ 91.37294597, 100.96781394, 100.40118279],
        [101.20862522, 103.5730309 , 100.28690912],
        [102.80387079,  98.29687616,  93.24376389],
        [106.71751618, 102.97585605,  98.45723272],
        [ 96.02548256, 102.82360856, 106.47551845],
        [105.30350449,  92.87730812, 103.19258339],
        [110.44484313,  93.87155456, 101.5363647 ],
        [101.3514185 , 100.37372248, 106.6471081 ],
        [ 97.21315663, 107.02874163, 102.17642112],
        [ 95.65982034, 107.22482426, 107.19119932],
        [100.39303522,  92.0108226 ,  97.75887636],
        [103.1521596 , 109.40523174,  93.83969256],
        [106.11454989,  88.80221141,  94.5081787 ],
        [ 96.78266211,  99.84251605, 104.03478031],
        [101.86186193, 103.61720152,  99.57859892],
        [ 97.49594839,  96.59385486, 104.63817694],
        [ 96

In [35]:
# split our dataset vertically on index 2
np.vsplit(dataset, (0, 2))

[array([], shape=(0, 8), dtype=float64),
 array([[ 99.14931546, 104.03852715, 107.43534677,  97.85230675,
          98.74986914,  98.80833412,  96.81964892,  98.56783189],
        [ 92.02628776,  97.10439252,  99.32066924,  97.24584816,
          92.9267508 ,  92.65657752, 105.7197853 , 101.23162942]]),
 array([[ 95.66253664,  95.17750125,  90.93318132, 110.18889465,
          98.80084371, 105.95297652,  98.37481387, 106.54654286],
        [ 91.37294597, 100.96781394, 100.40118279, 113.42090475,
         105.48508838,  91.6604946 , 106.1472841 ,  95.08715803],
        [101.20862522, 103.5730309 , 100.28690912, 105.85269352,
          93.37126331, 108.57980357, 100.79478953,  94.20019732],
        [102.80387079,  98.29687616,  93.24376389,  97.24130034,
          89.03452725,  96.2832753 , 104.60344836, 101.13442416],
        [106.71751618, 102.97585605,  98.45723272, 100.72418901,
         106.39798503,  95.46493436,  94.35373179, 106.83273763],
        [ 96.02548256, 102.82360856, 106

In [28]:
# iterating over the complete dataset
for x in np.nditer(dataset):
    print(x)

99.14931546
104.03852715
107.43534677
97.85230675
98.74986914
98.80833412
96.81964892
98.56783189
92.02628776
97.10439252
99.32066924
97.24584816
92.9267508
92.65657752
105.7197853
101.23162942
95.66253664
95.17750125
90.93318132
110.18889465
98.80084371
105.95297652
98.37481387
106.54654286
91.37294597
100.96781394
100.40118279
113.42090475
105.48508838
91.6604946
106.1472841
95.08715803
101.20862522
103.5730309
100.28690912
105.85269352
93.37126331
108.57980357
100.79478953
94.20019732
102.80387079
98.29687616
93.24376389
97.24130034
89.03452725
96.2832753
104.60344836
101.13442416
106.71751618
102.97585605
98.45723272
100.72418901
106.39798503
95.46493436
94.35373179
106.83273763
96.02548256
102.82360856
106.47551845
101.34745901
102.45651798
98.74767493
97.57544275
92.5748759
105.30350449
92.87730812
103.19258339
104.40518318
101.29326772
100.85447132
101.2226037
106.03868807
110.44484313
93.87155456
101.5363647
97.65393524
92.75048583
101.72074646
96.96851209
103.29147111
101.3514

In [29]:
# iterate over the whole dataset with indices
for i, x in np.ndenumerate(dataset):
    print(i, x)

(0, 0) 99.14931546
(0, 1) 104.03852715
(0, 2) 107.43534677
(0, 3) 97.85230675
(0, 4) 98.74986914
(0, 5) 98.80833412
(0, 6) 96.81964892
(0, 7) 98.56783189
(1, 0) 92.02628776
(1, 1) 97.10439252
(1, 2) 99.32066924
(1, 3) 97.24584816
(1, 4) 92.9267508
(1, 5) 92.65657752
(1, 6) 105.7197853
(1, 7) 101.23162942
(2, 0) 95.66253664
(2, 1) 95.17750125
(2, 2) 90.93318132
(2, 3) 110.18889465
(2, 4) 98.80084371
(2, 5) 105.95297652
(2, 6) 98.37481387
(2, 7) 106.54654286
(3, 0) 91.37294597
(3, 1) 100.96781394
(3, 2) 100.40118279
(3, 3) 113.42090475
(3, 4) 105.48508838
(3, 5) 91.6604946
(3, 6) 106.1472841
(3, 7) 95.08715803
(4, 0) 101.20862522
(4, 1) 103.5730309
(4, 2) 100.28690912
(4, 3) 105.85269352
(4, 4) 93.37126331
(4, 5) 108.57980357
(4, 6) 100.79478953
(4, 7) 94.20019732
(5, 0) 102.80387079
(5, 1) 98.29687616
(5, 2) 93.24376389
(5, 3) 97.24130034
(5, 4) 89.03452725
(5, 5) 96.2832753
(5, 6) 104.60344836
(5, 7) 101.13442416
(6, 0) 106.71751618
(6, 1) 102.97585605
(6, 2) 98.45723272
(6, 3) 100.724